services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flarenet-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_CONFIG_MAXMEMORY_POLICY=noeviction
    env_file:
      - .env.production